-- Alterando esquema e adicionando as tabelas de login

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS schema_migrations (
    versao VARCHAR(255) PRIMARY KEY,
    aplicada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS empresa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cnpj VARCHAR(18) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_empresa_cnpj
    ON empresa (cnpj);

CREATE TABLE IF NOT EXISTS usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    tentativas_login INTEGER NOT NULL DEFAULT 0,
    bloqueado_ate TIMESTAMPTZ,
    ultimo_login_em TIMESTAMPTZ,
    email_verificado_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_email
    ON usuario (LOWER(email));

CREATE INDEX IF NOT EXISTS ix_usuario_empresa
    ON usuario (empresa_id);

CREATE TABLE IF NOT EXISTS obra (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_obra_empresa
    ON obra (empresa_id);

CREATE TABLE IF NOT EXISTS produto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    unidade VARCHAR(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_produto_empresa
    ON produto (empresa_id);

CREATE TABLE IF NOT EXISTS equipamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    patrimonio VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_equipamento_patrimonio
    ON equipamento (empresa_id, patrimonio);

CREATE TABLE IF NOT EXISTS estoque (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    produto_id INTEGER NOT NULL REFERENCES produto(id) ON DELETE RESTRICT,
    quantidade NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade >= 0),
    CONSTRAINT ux_estoque_obra_produto UNIQUE (obra_id, produto_id)
);

CREATE TABLE IF NOT EXISTS pedido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    protocolo VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    justificativa VARCHAR(255),
    data TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pedido_protocolo
    ON pedido (protocolo);

CREATE INDEX IF NOT EXISTS ix_pedido_obra_status
    ON pedido (obra_id, status);

CREATE TABLE IF NOT EXISTS item_pedido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
    produto_id INTEGER NOT NULL REFERENCES produto(id) ON DELETE RESTRICT,
    quantidade NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_item_pedido_quantidade CHECK (quantidade > 0)
);

CREATE TABLE IF NOT EXISTS entrada_estoque (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    xml_nota_fiscal TEXT,
    justificativa VARCHAR(255),
    data TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS item_entrada (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada_id INTEGER NOT NULL REFERENCES entrada_estoque(id) ON DELETE CASCADE,
    produto_id INTEGER NOT NULL REFERENCES produto(id) ON DELETE RESTRICT,
    quantidade NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_item_entrada_quantidade CHECK (quantidade > 0)
);

CREATE TABLE IF NOT EXISTS emprestimo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento_id INTEGER NOT NULL REFERENCES equipamento(id) ON DELETE RESTRICT,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    data_emprestimo TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_devolucao TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_emprestimo_equipamento_status
    ON emprestimo (equipamento_id, status);

CREATE TABLE IF NOT EXISTS log_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    acao VARCHAR(255) NOT NULL,
    data TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_log_usuario_data
    ON log_sistema (usuario_id, data DESC);


CREATE TABLE IF NOT EXISTS sessao_usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    refresh_token_hash CHAR(64) NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    revogado_em TIMESTAMPTZ,
    endereco_ip INET,
    user_agent VARCHAR(500),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_sessao_usuario_ativa
    ON sessao_usuario (usuario_id, expira_em)
    WHERE revogado_em IS NULL;


CREATE TABLE IF NOT EXISTS recuperacao_senha (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    utilizado_em TIMESTAMPTZ,
    endereco_ip INET,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_recuperacao_senha_usuario
    ON recuperacao_senha (usuario_id, expira_em);


CREATE TABLE IF NOT EXISTS tentativa_login (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES usuario(id) ON DELETE SET NULL,
    email_hash CHAR(64) NOT NULL,
    endereco_ip INET,
    sucesso BOOLEAN NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_tentativa_login_email_data
    ON tentativa_login (email_hash, criado_em DESC);

CREATE INDEX IF NOT EXISTS ix_tentativa_login_ip_data
    ON tentativa_login (endereco_ip, criado_em DESC);

-- Marca as migrations correspondentes como aplicadas quando este schema
-- completo for utilizado para inicializar um banco novo.
INSERT INTO schema_migrations (versao)
VALUES ('001_schema_inicial.sql')
ON CONFLICT (versao) DO NOTHING;

INSERT INTO schema_migrations (versao)
VALUES ('002_tabelas_login.sql')
ON CONFLICT (versao) DO NOTHING;
