-- Schema consolidado do projeto Constroi.
-- Para bancos existentes, use o executor em constroi_api/bin/migrate.dart.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS schema_migrations (
    versao VARCHAR(255) PRIMARY KEY,
    aplicada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS empresa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cnpj VARCHAR(18) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_empresa_cnpj
    ON empresa (cnpj);

CREATE TABLE IF NOT EXISTS usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    CONSTRAINT ck_usuario_tipo
        CHECK (tipo IN ('pedreiro', 'engenheiro', 'master')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    tentativas_login INTEGER NOT NULL DEFAULT 0,
    bloqueado_ate TIMESTAMPTZ,
    ultimo_login_em TIMESTAMPTZ,
    email_verificado_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_email
    ON usuario (LOWER(email));

CREATE INDEX IF NOT EXISTS ix_usuario_empresa
    ON usuario (empresa_id);

CREATE TABLE IF NOT EXISTS obra (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_obra_empresa
    ON obra (empresa_id);

CREATE TABLE IF NOT EXISTS produto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    unidade VARCHAR(30) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_produto_empresa
    ON produto (empresa_id);

CREATE TABLE IF NOT EXISTS equipamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    patrimonio VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_equipamento_patrimonio
    ON equipamento (empresa_id, patrimonio);

CREATE TABLE IF NOT EXISTS estoque (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    produto_id INTEGER NOT NULL REFERENCES produto(id) ON DELETE RESTRICT,
    quantidade NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade >= 0),
    CONSTRAINT ux_estoque_obra_produto UNIQUE (obra_id, produto_id)
);

CREATE TABLE IF NOT EXISTS pedido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    protocolo VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    justificativa VARCHAR(255),
    data TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pedido_protocolo
    ON pedido (protocolo);

CREATE INDEX IF NOT EXISTS ix_pedido_obra_status
    ON pedido (obra_id, status);

CREATE TABLE IF NOT EXISTS item_pedido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
    produto_id INTEGER NOT NULL REFERENCES produto(id) ON DELETE RESTRICT,
    quantidade NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_item_pedido_quantidade CHECK (quantidade > 0)
);

CREATE TABLE IF NOT EXISTS entrada_estoque (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    xml_nota_fiscal TEXT,
    justificativa VARCHAR(255),
    data TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS item_entrada (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada_id INTEGER NOT NULL REFERENCES entrada_estoque(id) ON DELETE CASCADE,
    produto_id INTEGER NOT NULL REFERENCES produto(id) ON DELETE RESTRICT,
    quantidade NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_item_entrada_quantidade CHECK (quantidade > 0)
);

CREATE TABLE IF NOT EXISTS emprestimo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento_id INTEGER NOT NULL REFERENCES equipamento(id) ON DELETE RESTRICT,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    obra_id INTEGER NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    data_emprestimo TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_devolucao TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_emprestimo_equipamento_status
    ON emprestimo (equipamento_id, status);

CREATE TABLE IF NOT EXISTS log_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    acao VARCHAR(255) NOT NULL,
    data TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_log_usuario_data
    ON log_sistema (usuario_id, data DESC);


CREATE TABLE IF NOT EXISTS sessao_usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    refresh_token_hash CHAR(64) NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    revogado_em TIMESTAMPTZ,
    endereco_ip INET,
    user_agent VARCHAR(500),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_sessao_usuario_ativa
    ON sessao_usuario (usuario_id, expira_em)
    WHERE revogado_em IS NULL;


CREATE TABLE IF NOT EXISTS recuperacao_senha (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    utilizado_em TIMESTAMPTZ,
    endereco_ip INET,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_recuperacao_senha_usuario
    ON recuperacao_senha (usuario_id, expira_em);


CREATE TABLE IF NOT EXISTS tentativa_login (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES usuario(id) ON DELETE SET NULL,
    email_hash CHAR(64) NOT NULL,
    endereco_ip INET,
    sucesso BOOLEAN NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_tentativa_login_email_data
    ON tentativa_login (email_hash, criado_em DESC);

CREATE INDEX IF NOT EXISTS ix_tentativa_login_ip_data
    ON tentativa_login (endereco_ip, criado_em DESC);

-- Equipe: uma pessoa pode participar de varias obras da mesma empresa.
CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_id_empresa
    ON usuario (id, empresa_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_obra_id_empresa
    ON obra (id, empresa_id);

CREATE TABLE IF NOT EXISTS usuario_obra (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    obra_id INTEGER NOT NULL,
    data_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fim TIMESTAMPTZ,
    CONSTRAINT fk_usuario_obra_usuario_empresa
        FOREIGN KEY (usuario_id, empresa_id)
        REFERENCES usuario (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_obra_obra_empresa
        FOREIGN KEY (obra_id, empresa_id)
        REFERENCES obra (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT ck_usuario_obra_periodo
        CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_obra_ativo
    ON usuario_obra (usuario_id, obra_id)
    WHERE data_fim IS NULL;

CREATE INDEX IF NOT EXISTS ix_usuario_obra_obra_ativos
    ON usuario_obra (obra_id, usuario_id)
    WHERE data_fim IS NULL;

-- Custos: orçamento, preços históricos e despesas da obra.
ALTER TABLE obra
    ADD COLUMN IF NOT EXISTS orcamento_total NUMERIC(14, 2);

ALTER TABLE obra
    ADD CONSTRAINT ck_obra_orcamento_total
    CHECK (orcamento_total IS NULL OR orcamento_total >= 0);

CREATE TABLE IF NOT EXISTS categoria_custo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO categoria_custo (nome) VALUES
    ('Aço e vergalhão'),
    ('Cimento e agregados'),
    ('Locação de equipamentos'),
    ('Madeira e formas'),
    ('EPI e consumíveis')
ON CONFLICT (nome) DO NOTHING;

ALTER TABLE produto
    ADD COLUMN IF NOT EXISTS categoria_custo_id INTEGER
    REFERENCES categoria_custo (id) ON DELETE RESTRICT;

ALTER TABLE item_entrada
    ADD COLUMN IF NOT EXISTS valor_unitario NUMERIC(14, 2);

ALTER TABLE item_entrada
    ADD COLUMN IF NOT EXISTS categoria_custo_id INTEGER
    REFERENCES categoria_custo (id) ON DELETE RESTRICT;

ALTER TABLE item_entrada
    ADD CONSTRAINT ck_item_entrada_valor_unitario
    CHECK (valor_unitario IS NULL OR valor_unitario >= 0);

ALTER TABLE item_entrada
    ADD CONSTRAINT ck_item_entrada_valor_com_categoria
    CHECK (valor_unitario IS NULL OR categoria_custo_id IS NOT NULL);

CREATE INDEX IF NOT EXISTS ix_item_entrada_categoria_custo
    ON item_entrada (categoria_custo_id);

CREATE TABLE IF NOT EXISTS despesa_obra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL,
    obra_id INTEGER NOT NULL,
    registrado_por_usuario_id INTEGER NOT NULL,
    categoria_custo_id INTEGER NOT NULL
        REFERENCES categoria_custo (id) ON DELETE RESTRICT,
    descricao VARCHAR(255) NOT NULL,
    valor NUMERIC(14, 2) NOT NULL,
    data_lancamento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despesa_obra_empresa
        FOREIGN KEY (obra_id, empresa_id)
        REFERENCES obra (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT fk_despesa_usuario_empresa
        FOREIGN KEY (registrado_por_usuario_id, empresa_id)
        REFERENCES usuario (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT ck_despesa_valor CHECK (valor > 0),
    CONSTRAINT ck_despesa_descricao CHECK (LENGTH(TRIM(descricao)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_despesa_obra_data
    ON despesa_obra (obra_id, data_lancamento DESC);

CREATE INDEX IF NOT EXISTS ix_despesa_categoria
    ON despesa_obra (categoria_custo_id);

CREATE VIEW vw_lancamento_custo AS
SELECT
    'material'::TEXT AS origem,
    ie.id::BIGINT AS origem_id,
    ee.obra_id,
    ie.categoria_custo_id,
    ee.data AS data_lancamento,
    p.nome AS descricao,
    ROUND(ie.quantidade * ie.valor_unitario, 2) AS valor
FROM item_entrada AS ie
JOIN entrada_estoque AS ee ON ee.id = ie.entrada_id
JOIN produto AS p ON p.id = ie.produto_id
WHERE ie.valor_unitario IS NOT NULL
UNION ALL
SELECT
    'despesa'::TEXT AS origem,
    d.id AS origem_id,
    d.obra_id,
    d.categoria_custo_id,
    d.data_lancamento,
    d.descricao,
    d.valor
FROM despesa_obra AS d;

CREATE VIEW vw_resumo_custo_obra AS
SELECT
    o.id AS obra_id,
    o.orcamento_total,
    COALESCE(SUM(l.valor), 0) AS custo_acumulado,
    CASE WHEN o.orcamento_total IS NULL THEN NULL
         ELSE o.orcamento_total - COALESCE(SUM(l.valor), 0)
    END AS saldo_orcamento,
    CASE WHEN o.orcamento_total > 0
         THEN ROUND(COALESCE(SUM(l.valor), 0) * 100 / o.orcamento_total, 1)
         ELSE NULL
    END AS percentual_consumido
FROM obra AS o
LEFT JOIN vw_lancamento_custo AS l ON l.obra_id = o.id
GROUP BY o.id, o.orcamento_total;

-- Este arquivo representa o estado final depois das migrations 001 a 008.
INSERT INTO schema_migrations (versao) VALUES
    ('001_schema_inicial.sql'),
    ('002_tabelas_login.sql'),
    ('003_catalogo_timestamps.sql'),
    ('004_usuario_obra.sql'),
    ('005_custos_obra.sql'),
    ('006_usuario_tipo.sql'),
    ('007_corrige_colunas_legadas.sql'),
    ('008_protege_estoque.sql')
ON CONFLICT (versao) DO NOTHING;
