-- Estrutura necessaria para o login futuro
-- Senhas e tokens nunca devem ser armazenados em texto puro

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE usuario ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS tentativas_login INTEGER NOT NULL DEFAULT 0;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS bloqueado_ate TIMESTAMPTZ;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS ultimo_login_em TIMESTAMPTZ;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS email_verificado_em TIMESTAMPTZ;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS sessao_usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    refresh_token_hash CHAR(64) NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    revogado_em TIMESTAMPTZ,
    endereco_ip INET,
    user_agent VARCHAR(500),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_sessao_usuario_ativa
    ON sessao_usuario (usuario_id, expira_em)
    WHERE revogado_em IS NULL;

CREATE TABLE IF NOT EXISTS recuperacao_senha (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    utilizado_em TIMESTAMPTZ,
    endereco_ip INET,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_recuperacao_senha_usuario
    ON recuperacao_senha (usuario_id, expira_em);

CREATE TABLE IF NOT EXISTS tentativa_login (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES usuario(id) ON DELETE SET NULL,
    email_hash CHAR(64) NOT NULL,
    endereco_ip INET,
    sucesso BOOLEAN NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_tentativa_login_email_data
    ON tentativa_login (email_hash, criado_em DESC);

CREATE INDEX IF NOT EXISTS ix_tentativa_login_ip_data
    ON tentativa_login (endereco_ip, criado_em DESC);
