-- Uma pessoa pode participar de varias obras, desde que pertençam a mesma empresa.
-- Os indices compostos permitem que as duas chaves estrangeiras validem a empresa.
CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_id_empresa
    ON usuario (id, empresa_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_obra_id_empresa
    ON obra (id, empresa_id);

CREATE TABLE IF NOT EXISTS usuario_obra (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    obra_id INTEGER NOT NULL,
    data_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fim TIMESTAMPTZ,
    CONSTRAINT fk_usuario_obra_usuario_empresa
        FOREIGN KEY (usuario_id, empresa_id)
        REFERENCES usuario (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_obra_obra_empresa
        FOREIGN KEY (obra_id, empresa_id)
        REFERENCES obra (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT ck_usuario_obra_periodo
        CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

-- Um usuario pode voltar a obra no futuro, mas so pode ter um vinculo ativo por vez.
CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_obra_ativo
    ON usuario_obra (usuario_id, obra_id)
    WHERE data_fim IS NULL;

CREATE INDEX IF NOT EXISTS ix_usuario_obra_obra_ativos
    ON usuario_obra (obra_id, usuario_id)
    WHERE data_fim IS NULL;
