-- Dados necessarios para a tela 06_Custos do Figma.
-- Precos pagos ficam nos itens de entrada, preservando o historico de cada compra.

ALTER TABLE obra
    ADD COLUMN IF NOT EXISTS orcamento_total NUMERIC(14, 2);

ALTER TABLE obra
    ADD CONSTRAINT ck_obra_orcamento_total
    CHECK (orcamento_total IS NULL OR orcamento_total >= 0);

CREATE TABLE IF NOT EXISTS categoria_custo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO categoria_custo (nome) VALUES
    ('Aço e vergalhão'),
    ('Cimento e agregados'),
    ('Locação de equipamentos'),
    ('Madeira e formas'),
    ('EPI e consumíveis')
ON CONFLICT (nome) DO NOTHING;

-- Categoria do produto é uma sugestão para compras futuras.
-- A categoria do item de entrada é a classificação histórica da compra.
ALTER TABLE produto
    ADD COLUMN IF NOT EXISTS categoria_custo_id INTEGER
    REFERENCES categoria_custo (id) ON DELETE RESTRICT;

ALTER TABLE item_entrada
    ADD COLUMN IF NOT EXISTS valor_unitario NUMERIC(14, 2);

ALTER TABLE item_entrada
    ADD COLUMN IF NOT EXISTS categoria_custo_id INTEGER
    REFERENCES categoria_custo (id) ON DELETE RESTRICT;

ALTER TABLE item_entrada
    ADD CONSTRAINT ck_item_entrada_valor_unitario
    CHECK (valor_unitario IS NULL OR valor_unitario >= 0);

ALTER TABLE item_entrada
    ADD CONSTRAINT ck_item_entrada_valor_com_categoria
    CHECK (valor_unitario IS NULL OR categoria_custo_id IS NOT NULL);

CREATE INDEX IF NOT EXISTS ix_item_entrada_categoria_custo
    ON item_entrada (categoria_custo_id);

-- Gastos que não são entrada de material: locação, serviços e similares.
-- A empresa é conferida nas duas chaves estrangeiras compostas criadas na 004.
CREATE TABLE IF NOT EXISTS despesa_obra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL,
    obra_id INTEGER NOT NULL,
    registrado_por_usuario_id INTEGER NOT NULL,
    categoria_custo_id INTEGER NOT NULL
        REFERENCES categoria_custo (id) ON DELETE RESTRICT,
    descricao VARCHAR(255) NOT NULL,
    valor NUMERIC(14, 2) NOT NULL,
    data_lancamento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despesa_obra_empresa
        FOREIGN KEY (obra_id, empresa_id)
        REFERENCES obra (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT fk_despesa_usuario_empresa
        FOREIGN KEY (registrado_por_usuario_id, empresa_id)
        REFERENCES usuario (id, empresa_id) ON DELETE RESTRICT,
    CONSTRAINT ck_despesa_valor CHECK (valor > 0),
    CONSTRAINT ck_despesa_descricao CHECK (LENGTH(TRIM(descricao)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_despesa_obra_data
    ON despesa_obra (obra_id, data_lancamento DESC);

CREATE INDEX IF NOT EXISTS ix_despesa_categoria
    ON despesa_obra (categoria_custo_id);

-- Fonte unica para os totais: compras com preço registrado + outras despesas.
-- Um material comprado não deve ser repetido em despesa_obra.
CREATE VIEW vw_lancamento_custo AS
SELECT
    'material'::TEXT AS origem,
    ie.id::BIGINT AS origem_id,
    ee.obra_id,
    ie.categoria_custo_id,
    ee.data AS data_lancamento,
    p.nome AS descricao,
    ROUND(ie.quantidade * ie.valor_unitario, 2) AS valor
FROM item_entrada AS ie
JOIN entrada_estoque AS ee ON ee.id = ie.entrada_id
JOIN produto AS p ON p.id = ie.produto_id
WHERE ie.valor_unitario IS NOT NULL
UNION ALL
SELECT
    'despesa'::TEXT AS origem,
    d.id AS origem_id,
    d.obra_id,
    d.categoria_custo_id,
    d.data_lancamento,
    d.descricao,
    d.valor
FROM despesa_obra AS d;

CREATE VIEW vw_resumo_custo_obra AS
SELECT
    o.id AS obra_id,
    o.orcamento_total,
    COALESCE(SUM(l.valor), 0) AS custo_acumulado,
    CASE WHEN o.orcamento_total IS NULL THEN NULL
         ELSE o.orcamento_total - COALESCE(SUM(l.valor), 0)
    END AS saldo_orcamento,
    CASE WHEN o.orcamento_total > 0
         THEN ROUND(COALESCE(SUM(l.valor), 0) * 100 / o.orcamento_total, 1)
         ELSE NULL
    END AS percentual_consumido
FROM obra AS o
LEFT JOIN vw_lancamento_custo AS l ON l.obra_id = o.id
GROUP BY o.id, o.orcamento_total;
